name: Build Maven Project

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # Install Adoptium's Temurin distribution of OpenJDK
        cache: 'maven'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y /tmp/chrome.deb

    - name: Run tests with Xvfb
      run: |
        sudo Xvfb :99 -ac -screen 0 1280x1024x16 &
        export DISPLAY=:99
        mvn test
